import re
# ================================================
# FIX BROKEN LINES (MOST IMPORTANT FEATURE)
# ================================================
def fix_broken_lines(text):
    """
    Reconstruct paragraphs from PDF text.
    - Fixes wrapped lines
    - Preserves court headings
    - Preserves bullets (•, -, 1., 3.2 etc.)
    - Preserves VERSUS block
    """
    lines = text.split("\n")
    final_lines = []
    buffer = ""
    for line in lines:
        stripped = line.strip()
        # Blank line → paragraph break
        if stripped == "":
            if buffer:
                final_lines.append(buffer.strip())
                buffer = ""
            final_lines.append("")
            continue
        # Keep headings (UPPERCASE lines)
        if stripped.isupper() and len(stripped.split()) > 1:
            if buffer:
                final_lines.append(buffer.strip())
                buffer = ""
            final_lines.append(stripped)
            continue
        # Bullet / numbered line → new paragraph
        if re.match(r"^(\d+\.)|(\d+\.\d+)|(- |•)", stripped):
            if buffer:
                final_lines.append(buffer.strip())
                buffer = ""
            final_lines.append(stripped)
            continue
        # If previous line ends properly → new paragraph
        if buffer.endswith((".", "?", "!", ":")):
            final_lines.append(buffer)
            buffer = stripped
        else:
            # merge normal wrapped lines
            buffer += " " + stripped if buffer else stripped
    # Add any remaining buffer
    if buffer:
        final_lines.append(buffer.strip())
    return "\n".join(final_lines)
# ================================================
# MAIN CLEANER
# ================================================
def clean_extracted_text(text):
    """
    PRO legal cleaner:
    - Removes headers / footers
    - Removes OCR garbage
    - Preserves court name, parties, metadata
    - Ensures readable paragraphs
    """
    # Normalize line endings
    text = text.replace("\r", "")
    lines = text.split("\n")
    cleaned = []
    force_keep_next_two = False
    # -------- RULES BEGIN --------
    for idx, org_line in enumerate(lines):
        line = org_line.strip()
        # Keep blank lines (controls paragraph structure)
        if line == "":
            cleaned.append("")
            continue
        # Keep Court names
        if re.search(r"(SUPREME COURT|HIGH COURT|DISTRICT COURT)", line, re.I):
            cleaned.append(org_line)
            continue
        # Preserve party block
        if line.upper() in ["VERSUS", "VS", "V."]:
            cleaned.append(line)
            force_keep_next_two = 2
            continue
        if force_keep_next_two:
            cleaned.append(org_line)
            force_keep_next_two -= 1
            continue
        # Keep party metadata
        important_metadata_keywords = [
            "APPELLANT", "RESPONDENT", "PETITIONER", "APPLICANT",
            "CORAM", "BENCH", "PRESENT", "BEFORE"
        ]
        if any(k in line.upper() for k in important_metadata_keywords):
            cleaned.append(org_line)
            continue
        # Remove garbage headers
        header_garbage = [
            "APPELLATE JURISDICTION",
            "REPORTABLE", "UNREPORTABLE", "NON-REPORTABLE",
            "Digitally signed", "Signature Not Verified",
            "Downloaded from", "Generated by"
        ]
        if any(h.upper() in line.upper() for h in header_garbage):
            continue
        # Remove page number lines
        if re.search(r"Page\s*\d+\s*of\s*\d+", line, re.I):
            continue
        if re.fullmatch(r"\d+", line):
            continue
        if re.match(r"^\[\d+\]$", line):  # like [3]
            continue
        # Remove repeated case number footer EXCEPT header
        if re.search(r"(SLP|W\.P|W\.A|Crl\.A|Cr\.A)\.?\s*\d+\/\d+", line, re.I):
            if idx < 3:
                cleaned.append(org_line)
            continue
        # Remove uppercase garbage except important ones
        if line.isupper():
            keep = ["APPELLANT", "RESPONDENT", "ANR", "CORAM", "SECTION", "ACT"]
            if not any(k in line for k in keep):
                continue
        # Remove separators like "------"
        if re.fullmatch(r"[\.\-=*_]{4,}", line):
            continue
        # Remove advocate lines
        if re.search(r"advocate|for the appellant|for the respondent", line, re.I):
            continue
        # Remove meaningless tiny lines
        if len(line) <= 2 and not line.isalpha():
            continue
        cleaned.append(org_line)
    # -------------------------------
    # Combine cleaned lines
    # -------------------------------
    cleaned_text = "\n".join(cleaned)
    # Normalize excessive spacing
    cleaned_text = re.sub(r"\n{3,}", "\n\n", cleaned_text)
    # Fix paragraph structure (IMPORTANT)
    cleaned_text = fix_broken_lines(cleaned_text)
    # Trim
    cleaned_text = cleaned_text.strip()
    return cleaned_text
